packages:
  - name: schema
    type: generic
    srcs:
      - "schema/*.yaml"

  - name: lib
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
      - "schema/*.yaml"
    deps:
      - components/spicedb:schema
    env:
      - CGO_ENABLED=0
    config:
      packaging: library
scripts:
  - name: start-spicedb
    description: "Starts spicedb if not already running."
    deps: []
    script: |
      leeway run components/spicedb:stop-spicedb && docker run --rm --name test-spicedb -p50051:50051 -v $(pwd)/schema/schema.yaml:/schema.yaml -d authzed/spicedb serve-testing --load-configs /schema.yaml && echo "Started spicedb."
  - name: stop-spicedb
    description: "Stops spicedb if running."
    deps: []
    script: |
      if docker stop test-spicedb > /dev/null 2>&1; then
          echo "Stopped spicedb."
      fi
  - name: report-spicedb
    description: "Reports spicedb's current state."
    deps: []
    script: |
      spicedn
